"""
06_build_sales_all_meters.py

Build the governed Sales All Meters staging CSV from:
- one approved Meter Master CSV; and
- the complete validated range of monthly meter-level sales CSVs.

The builder is environment-neutral. It does not connect to Firebase.

Example
-------
python .\\scripts\\06_build_sales_all_meters.py `
  --lm-pcode ZA7423 `
  --from-month 2025-09 `
  --to-month 2026-06 `
  --master .\\output\\meter_master\\meter_master__ZA7423__FULL__2025-09_to_2026-06.csv `
  --monthly-dir .\\output\\monthly `
  --output .\\output\\sales_all_meters\\sales_all_meters__ZA7423__FULL__2025-09_to_2026-06.csv
"""

from __future__ import annotations

import argparse
import re
from dataclasses import dataclass
from datetime import UTC, date, datetime
from decimal import Decimal, InvalidOperation
from pathlib import Path
from typing import Any, Iterable

import pandas as pd


PROJECT_ROOT = Path(__file__).resolve().parents[1]
MONTH_RE = re.compile(r"^(\d{4})-(\d{2})$")
MONTHLY_FILENAME_RE = re.compile(
    r"^monthly__FULL__(\d{4}-\d{2})__from_atomic\.csv$",
    re.IGNORECASE,
)
METER_RE = re.compile(r"^[A-Z0-9._/-]+$")

MASTER_COLUMNS = [
    "masterId",
    "lmPcode",
    "meterNoRaw",
    "meterNoNormalized",
    "meterType",
    "customerNo",
    "accountNo",
    "salesId",
    "salesProvider",
    "astId",
]

MONTHLY_REQUIRED_COLUMNS = [
    "lmPcode",
    "meterNo",
    "ym",
    "amountTotalC",
    "lastPurchaseAtISO",
]

BASE_OUTPUT_COLUMNS = [
    "masterId",
    "visibility",
    "meterNo",
    "meterNoNormalized",
    "provider",
    "customerNo",
    "accountNo",
    "totalAmountC",
    "lastPurchaseAtISO",
    "daysSinceLastPurchase",
]


@dataclass(frozen=True)
class BuildConfig:
    lm_pcode: str
    from_month: str
    to_month: str
    master_path: Path
    monthly_dir: Path
    output_path: Path
    as_of_date: date


@dataclass
class BuildStats:
    master_rows: int = 0
    monthly_rows: int = 0
    meters_with_sales: int = 0
    meters_without_sales: int = 0
    visible_meters: int = 0
    invisible_meters: int = 0


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Build a governed Sales All Meters CSV from an approved Meter Master "
            "CSV and dynamically discovered monthly meter-level sales files."
        )
    )
    parser.add_argument("--lm-pcode", required=True, help="LM/workbase code, for example ZA7423.")
    parser.add_argument("--from-month", required=True, help="First included month in YYYY-MM format.")
    parser.add_argument("--to-month", required=True, help="Last included month in YYYY-MM format.")
    parser.add_argument(
        "--master",
        required=True,
        type=Path,
        help="Approved Meter Master CSV generated by 05_build_meter_master_v3.py.",
    )
    parser.add_argument(
        "--monthly-dir",
        type=Path,
        default=Path("output/monthly"),
        help="Directory containing monthly__FULL__YYYY-MM__from_atomic.csv files.",
    )
    parser.add_argument(
        "--output",
        required=True,
        type=Path,
        help="Output Sales All Meters CSV path.",
    )
    parser.add_argument(
        "--as-of-date",
        type=str,
        default=datetime.now(UTC).date().isoformat(),
        help=(
            "Date used to calculate daysSinceLastPurchase, in YYYY-MM-DD format. "
            "Defaults to the current UTC date."
        ),
    )
    return parser.parse_args()


def resolve_project_path(path: Path) -> Path:
    return path if path.is_absolute() else PROJECT_ROOT / path


def safe_str(value: Any) -> str:
    if value is None or pd.isna(value):
        return ""
    text = str(value).strip()
    return "" if text.lower() == "nan" else text


def normalize_meter_no(value: Any) -> str:
    return re.sub(r"\s+", "", safe_str(value)).upper()


def validate_meter_no(value: str, label: str, row_number: int) -> None:
    if not value:
        raise ValueError(f"{label} is blank at row {row_number}.")
    if not METER_RE.fullmatch(value):
        raise ValueError(
            f"{label} contains invalid characters at row {row_number}: {value!r}"
        )


def parse_month(value: str, label: str) -> tuple[int, int]:
    match = MONTH_RE.fullmatch(safe_str(value))
    if not match:
        raise ValueError(f"{label} must use YYYY-MM format: {value!r}")
    year, month = int(match.group(1)), int(match.group(2))
    if not 1 <= month <= 12:
        raise ValueError(f"{label} has an invalid month: {value!r}")
    return year, month


def month_range(from_month: str, to_month: str) -> list[str]:
    start_year, start_month = parse_month(from_month, "--from-month")
    end_year, end_month = parse_month(to_month, "--to-month")
    if (start_year, start_month) > (end_year, end_month):
        raise ValueError("--from-month may not be later than --to-month.")

    result: list[str] = []
    year, month = start_year, start_month
    while (year, month) <= (end_year, end_month):
        result.append(f"{year:04d}-{month:02d}")
        month += 1
        if month == 13:
            month = 1
            year += 1
    return result


def parse_iso(value: Any, label: str, row_number: int) -> datetime | None:
    text = safe_str(value)
    if not text:
        return None
    try:
        parsed = datetime.fromisoformat(text.replace("Z", "+00:00"))
    except ValueError as exc:
        raise ValueError(
            f"{label} is not a valid ISO timestamp at row {row_number}: {text!r}"
        ) from exc
    if parsed.tzinfo is None:
        raise ValueError(
            f"{label} must include a timezone at row {row_number}: {text!r}"
        )
    return parsed.astimezone(UTC)


def parse_nonnegative_int(value: Any, label: str, row_number: int) -> int:
    text = safe_str(value)
    if not text:
        return 0
    try:
        number = Decimal(text)
    except InvalidOperation as exc:
        raise ValueError(f"{label} is not numeric at row {row_number}: {text!r}") from exc
    if number != number.to_integral_value():
        raise ValueError(f"{label} is not a whole number at row {row_number}: {text!r}")
    integer = int(number)
    if integer < 0:
        raise ValueError(f"{label} may not be negative at row {row_number}: {integer}")
    return integer


def parse_as_of_date(value: str) -> date:
    try:
        return date.fromisoformat(value)
    except ValueError as exc:
        raise ValueError(f"--as-of-date must use YYYY-MM-DD format: {value!r}") from exc


def require_file(path: Path, label: str) -> None:
    if not path.is_file():
        raise FileNotFoundError(f"{label} not found: {path}")


def require_directory(path: Path, label: str) -> None:
    if not path.is_dir():
        raise FileNotFoundError(f"{label} not found: {path}")


def discover_monthly_files(monthly_dir: Path, months: Iterable[str]) -> dict[str, Path]:
    expected_months = list(months)
    discovered: dict[str, Path] = {}

    for path in monthly_dir.iterdir():
        if not path.is_file():
            continue
        match = MONTHLY_FILENAME_RE.fullmatch(path.name)
        if not match:
            continue
        ym = match.group(1)
        if ym not in expected_months:
            continue
        if ym in discovered:
            raise ValueError(
                f"Multiple monthly files found for {ym}: {discovered[ym]} and {path}"
            )
        discovered[ym] = path.resolve()

    missing = [ym for ym in expected_months if ym not in discovered]
    if missing:
        raise FileNotFoundError(
            "Required monthly meter-level files are missing for: " + ", ".join(missing)
        )

    return {ym: discovered[ym] for ym in expected_months}


def validate_output_filename(path: Path, from_month: str, to_month: str) -> None:
    required_text = f"{from_month}_to_{to_month}"
    if required_text not in path.name:
        raise ValueError(
            "Output filename must accurately state the included range. "
            f"Expected filename to contain {required_text!r}: {path.name!r}"
        )


def load_master(config: BuildConfig, stats: BuildStats) -> dict[str, dict[str, Any]]:
    df = pd.read_csv(config.master_path, dtype=str, encoding="utf-8-sig").fillna("")
    actual_columns = list(df.columns)
    if actual_columns != MASTER_COLUMNS:
        raise ValueError(
            "Meter Master columns do not match the approved ten-column contract. "
            f"Expected={MASTER_COLUMNS}; actual={actual_columns}"
        )
    if df.empty:
        raise ValueError("Meter Master CSV contains zero rows.")

    records: dict[str, dict[str, Any]] = {}
    for row_number, row in enumerate(df.to_dict("records"), start=2):
        master_id = normalize_meter_no(row.get("masterId"))
        normalized = normalize_meter_no(row.get("meterNoNormalized"))
        raw = safe_str(row.get("meterNoRaw"))
        lm_pcode = safe_str(row.get("lmPcode"))
        sales_id = normalize_meter_no(row.get("salesId"))
        provider = safe_str(row.get("salesProvider"))

        validate_meter_no(master_id, "masterId", row_number)
        validate_meter_no(normalized, "meterNoNormalized", row_number)
        validate_meter_no(sales_id, "salesId", row_number)

        if "/" in master_id:
            raise ValueError(f"masterId may not contain '/': {master_id!r}")
        if master_id != normalized:
            raise ValueError(
                f"masterId must equal meterNoNormalized at row {row_number}: "
                f"{master_id!r} != {normalized!r}"
            )
        if sales_id != normalized:
            raise ValueError(
                f"salesId must equal meterNoNormalized at row {row_number}: "
                f"{sales_id!r} != {normalized!r}"
            )
        if lm_pcode != config.lm_pcode:
            raise ValueError(
                f"Meter Master LM mismatch at row {row_number}: "
                f"expected {config.lm_pcode!r}, found {lm_pcode!r}"
            )
        if not provider:
            raise ValueError(f"salesProvider is blank at row {row_number}.")
        if master_id in records:
            raise ValueError(f"Duplicate masterId in Meter Master: {master_id!r}")

        ast_id = safe_str(row.get("astId"))
        records[master_id] = {
            "masterId": master_id,
            "visibility": "VISIBLE" if ast_id else "INVISIBLE",
            "meterNo": raw,
            "meterNoNormalized": normalized,
            "provider": provider,
            "customerNo": safe_str(row.get("customerNo")),
            "accountNo": safe_str(row.get("accountNo")),
            "months": {},
            "totalAmountC": 0,
            "lastPurchase": None,
        }

    stats.master_rows = len(records)
    return records


def load_monthly_files(
    config: BuildConfig,
    monthly_files: dict[str, Path],
    records: dict[str, dict[str, Any]],
    stats: BuildStats,
) -> None:
    unknown_meters: list[tuple[str, str, int]] = []

    for ym, path in monthly_files.items():
        df = pd.read_csv(path, dtype=str, encoding="utf-8-sig").fillna("")
        missing_columns = [column for column in MONTHLY_REQUIRED_COLUMNS if column not in df.columns]
        if missing_columns:
            raise ValueError(f"{path} is missing required columns: {missing_columns}")

        seen_meters: set[str] = set()
        for row_number, row in enumerate(df.to_dict("records"), start=2):
            row_lm = safe_str(row.get("lmPcode"))
            row_ym = safe_str(row.get("ym"))
            meter = normalize_meter_no(row.get("meterNo"))

            if row_lm != config.lm_pcode:
                raise ValueError(
                    f"{path} contains LM {row_lm!r} at row {row_number}; "
                    f"expected only {config.lm_pcode!r}."
                )
            if row_ym != ym:
                raise ValueError(
                    f"{path} contains ym={row_ym!r} at row {row_number}; expected {ym!r}."
                )
            validate_meter_no(meter, "meterNo", row_number)
            if meter in seen_meters:
                raise ValueError(f"{path} contains duplicate meter {meter!r} for month {ym}.")
            seen_meters.add(meter)

            record = records.get(meter)
            if record is None:
                if len(unknown_meters) < 20:
                    unknown_meters.append((ym, meter, row_number))
                continue

            amount = parse_nonnegative_int(row.get("amountTotalC"), "amountTotalC", row_number)
            purchase = parse_iso(row.get("lastPurchaseAtISO"), "lastPurchaseAtISO", row_number)

            record["months"][ym] = amount
            record["totalAmountC"] += amount
            if purchase is not None and (
                record["lastPurchase"] is None or purchase > record["lastPurchase"]
            ):
                record["lastPurchase"] = purchase
            stats.monthly_rows += 1

    if unknown_meters:
        examples = ", ".join(
            f"{ym}:{meter} (row {row_number})"
            for ym, meter, row_number in unknown_meters[:10]
        )
        raise ValueError(
            "Monthly sales contain meter(s) absent from the approved Meter Master. "
            f"Examples: {examples}"
        )


def finalize_rows(
    config: BuildConfig,
    months: list[str],
    records: dict[str, dict[str, Any]],
    stats: BuildStats,
) -> pd.DataFrame:
    rows: list[dict[str, Any]] = []
    for record in records.values():
        last_purchase: datetime | None = record["lastPurchase"]
        if last_purchase is None:
            last_purchase_iso = ""
            days_since: int | str = ""
        else:
            last_purchase_iso = last_purchase.isoformat().replace("+00:00", "Z")
            days_since_value = (config.as_of_date - last_purchase.date()).days
            if days_since_value < 0:
                raise ValueError(
                    f"Last purchase for {record['masterId']} occurs after --as-of-date: "
                    f"{last_purchase_iso} > {config.as_of_date.isoformat()}"
                )
            days_since = days_since_value

        row: dict[str, Any] = {
            "masterId": record["masterId"],
            "visibility": record["visibility"],
            "meterNo": record["meterNo"],
            "meterNoNormalized": record["meterNoNormalized"],
            "provider": record["provider"],
            "customerNo": record["customerNo"],
            "accountNo": record["accountNo"],
            "totalAmountC": record["totalAmountC"],
            "lastPurchaseAtISO": last_purchase_iso,
            "daysSinceLastPurchase": days_since,
        }
        for ym in months:
            row[f"amount_{ym.replace('-', '_')}_C"] = record["months"].get(ym, 0)
        rows.append(row)

        if record["totalAmountC"] > 0:
            stats.meters_with_sales += 1
        else:
            stats.meters_without_sales += 1
        if record["visibility"] == "VISIBLE":
            stats.visible_meters += 1
        else:
            stats.invisible_meters += 1

    monthly_columns = [f"amount_{ym.replace('-', '_')}_C" for ym in months]
    output_columns = BASE_OUTPUT_COLUMNS + monthly_columns
    df = pd.DataFrame(rows, columns=output_columns)
    return df.sort_values(
        by=["meterNoNormalized", "meterNo"],
        ascending=[True, True],
        kind="stable",
    ).reset_index(drop=True)


def validate_output(df: pd.DataFrame, months: list[str], expected_rows: int) -> None:
    if len(df) != expected_rows:
        raise ValueError(f"Output row count mismatch: expected {expected_rows}, found {len(df)}")
    if df.empty:
        raise ValueError("Sales All Meters output contains zero rows.")
    if df["masterId"].eq("").any():
        raise ValueError("Sales All Meters output contains blank masterId values.")
    if df["masterId"].duplicated().any():
        examples = df.loc[df["masterId"].duplicated(keep=False), "masterId"].head(10).tolist()
        raise ValueError(f"Sales All Meters output contains duplicate masterId values: {examples}")
    if not (df["masterId"] == df["meterNoNormalized"]).all():
        raise ValueError("Sales All Meters output contains masterId/meterNoNormalized mismatches.")
    if not df["visibility"].isin(["VISIBLE", "INVISIBLE"]).all():
        raise ValueError("Sales All Meters output contains invalid visibility values.")

    monthly_columns = [f"amount_{ym.replace('-', '_')}_C" for ym in months]
    calculated_totals = df[monthly_columns].astype("int64").sum(axis=1)
    reported_totals = df["totalAmountC"].astype("int64")
    mismatches = calculated_totals != reported_totals
    if mismatches.any():
        sample = df.loc[mismatches, ["masterId", "totalAmountC"] + monthly_columns].head(10)
        raise ValueError(
            "totalAmountC does not reconcile to the included monthly columns. Examples:\n"
            + sample.to_string(index=False)
        )


def build_config(args: argparse.Namespace) -> BuildConfig:
    lm_pcode = safe_str(args.lm_pcode).upper()
    if not lm_pcode:
        raise ValueError("--lm-pcode may not be blank.")
    months = month_range(args.from_month, args.to_month)
    if not months:
        raise ValueError("The requested month range is empty.")

    config = BuildConfig(
        lm_pcode=lm_pcode,
        from_month=months[0],
        to_month=months[-1],
        master_path=resolve_project_path(args.master).resolve(),
        monthly_dir=resolve_project_path(args.monthly_dir).resolve(),
        output_path=resolve_project_path(args.output).resolve(),
        as_of_date=parse_as_of_date(args.as_of_date),
    )
    validate_output_filename(config.output_path, config.from_month, config.to_month)
    return config


def main() -> None:
    args = parse_args()
    config = build_config(args)
    months = month_range(config.from_month, config.to_month)
    stats = BuildStats()

    require_file(config.master_path, "Meter Master CSV")
    require_directory(config.monthly_dir, "Monthly output directory")
    monthly_files = discover_monthly_files(config.monthly_dir, months)

    print("=== SALES ALL METERS BUILD ===")
    print(f"Repository root: {PROJECT_ROOT}")
    print(f"LM/workbase:     {config.lm_pcode}")
    print(f"Meter Master:    {config.master_path}")
    print(f"As-of date:      {config.as_of_date.isoformat()}")
    print(f"Months:          {len(months)} ({months[0]} to {months[-1]})")
    for ym, path in monthly_files.items():
        print(f"  - {ym}: {path}")

    records = load_master(config, stats)
    load_monthly_files(config, monthly_files, records, stats)
    df = finalize_rows(config, months, records, stats)
    validate_output(df, months, stats.master_rows)

    config.output_path.parent.mkdir(parents=True, exist_ok=True)
    df.to_csv(config.output_path, index=False, encoding="utf-8")

    print("=== BUILD SUMMARY ===")
    print(f"Meter Master rows:       {stats.master_rows:,}")
    print(f"Monthly rows merged:     {stats.monthly_rows:,}")
    print(f"Meters with sales:       {stats.meters_with_sales:,}")
    print(f"Meters without sales:    {stats.meters_without_sales:,}")
    print(f"Visible meters:          {stats.visible_meters:,}")
    print(f"Invisible meters:        {stats.invisible_meters:,}")
    print(f"Total output rows:       {len(df):,}")
    print("Total reconciliation:    PASS")
    print("Validation:              PASS")
    print(f"Output:                  {config.output_path}")


if __name__ == "__main__":
    main()
