"""
06_build_sales_all_meters.py

Build the governed Sales All Meters staging CSV from:
- one approved Meter Master CSV; and
- the complete validated range of monthly meter-level sales CSVs.

Operational visibility is deliberately excluded. This stage must not derive
visibility from Meter Master astId or write a visibility column.

The builder is environment-neutral. It does not connect to Firebase.
It verifies the matching Stage 05 manifest and writes a frozen Stage 06 manifest
that Stage 08 must verify before upload.

Example
-------
python .\\scripts\\06_build_sales_all_meters.py `
  --lm-pcode ZA7423 `
  --from-month 2025-09 `
  --to-month 2026-06 `
  --master .\\output\\meter_master\\meter_master__ZA7423__FULL__2025-09_to_2026-06.csv `
  --master-manifest .\\output\\meter_master\\meter_master__ZA7423__FULL__2025-09_to_2026-06.manifest.json `
  --monthly-dir .\\output\\monthly `
  --output .\\output\\sales_all_meters\\sales_all_meters__ZA7423__FULL__2025-09_to_2026-06.csv `
  --as-of-date 2026-07-14
"""

from __future__ import annotations

import argparse
import hashlib
import io
import json
import re
from dataclasses import dataclass
from datetime import UTC, date, datetime
from decimal import Decimal, InvalidOperation
from pathlib import Path
from typing import Any, Iterable, Mapping, Sequence

import pandas as pd


PROJECT_ROOT = Path(__file__).resolve().parents[1]
GOVERNED_OUTPUT_DIR = (PROJECT_ROOT / "output" / "sales_all_meters").resolve()
GOVERNED_PROVIDER = "conlog"
GOVERNED_METER_TYPE = "electricity"
MANIFEST_SCHEMA_VERSION = 1
MONTH_RE = re.compile(r"^(\d{4})-(\d{2})$")
MONTHLY_FILENAME_RE = re.compile(
    r"^monthly__FULL__(\d{4}-\d{2})__from_atomic\.csv$",
    re.IGNORECASE,
)
METER_RE = re.compile(r"^[A-Z0-9]+$")

MASTER_COLUMNS = [
    "masterId",
    "lmPcode",
    "meterNoRaw",
    "meterNoNormalized",
    "meterType",
    "customerNo",
    "accountNo",
    "salesId",
    "salesProvider",
    "astId",
]

MONTHLY_REQUIRED_COLUMNS = [
    "lmPcode",
    "meterNo",
    "ym",
    "amountTotalC",
    "lastPurchaseAtISO",
]

MONTHLY_COLUMNS = [
    "docId",
    "lmPcode",
    "meterNo",
    "ym",
    "y",
    "m",
    "purchasesCount",
    "amountTotalC",
    "costC",
    "vatC",
    "firstPurchaseAtISO",
    "lastPurchaseAtISO",
    "firstPurchaseAtMs",
    "lastPurchaseAtMs",
    "salesGroupId",
    "salesGroupLabel",
]

BASE_OUTPUT_COLUMNS = [
    "masterId",
    "meterNo",
    "meterNoNormalized",
    "provider",
    "customerNo",
    "accountNo",
    "totalAmountC",
    "lastPurchaseAtISO",
    "daysSinceLastPurchase",
]


@dataclass(frozen=True)
class BuildConfig:
    lm_pcode: str
    from_month: str
    to_month: str
    master_path: Path
    master_manifest_path: Path
    monthly_dir: Path
    output_path: Path
    manifest_path: Path
    as_of_date: date


@dataclass
class BuildStats:
    master_rows: int = 0
    monthly_rows: int = 0
    meters_with_sales: int = 0
    meters_without_sales: int = 0


@dataclass(frozen=True)
class CsvSnapshot:
    """A parsed CSV and SHA produced from one immutable byte read."""

    path: Path
    frame: pd.DataFrame
    sha256: str


@dataclass(frozen=True)
class JsonSnapshot:
    """A parsed JSON object and SHA produced from one immutable byte read."""

    path: Path
    payload: dict[str, Any]
    sha256: str


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Build a governed Sales All Meters CSV from an approved Meter Master "
            "CSV and dynamically discovered monthly meter-level sales files."
        )
    )
    parser.add_argument("--lm-pcode", required=True, help="LM/workbase code, for example ZA7423.")
    parser.add_argument("--from-month", required=True, help="First included month in YYYY-MM format.")
    parser.add_argument("--to-month", required=True, help="Last included month in YYYY-MM format.")
    parser.add_argument(
        "--master",
        required=True,
        type=Path,
        help="Approved Meter Master CSV generated by 05_build_meter_master_v3.py.",
    )
    parser.add_argument(
        "--master-manifest",
        required=True,
        type=Path,
        help="Matching successful Stage 05 frozen-build manifest.",
    )
    parser.add_argument(
        "--monthly-dir",
        type=Path,
        default=Path("output/monthly"),
        help="Directory containing monthly__FULL__YYYY-MM__from_atomic.csv files.",
    )
    parser.add_argument(
        "--output",
        required=True,
        type=Path,
        help="Output Sales All Meters CSV path.",
    )
    parser.add_argument(
        "--as-of-date",
        required=True,
        type=str,
        help="Governed date used to calculate daysSinceLastPurchase, in YYYY-MM-DD format.",
    )
    return parser.parse_args()


def resolve_project_path(path: Path) -> Path:
    return path if path.is_absolute() else PROJECT_ROOT / path


def safe_str(value: Any) -> str:
    if value is None or pd.isna(value):
        return ""
    text = str(value).strip()
    return "" if text.lower() == "nan" else text


def normalize_meter_no(value: Any) -> str:
    return re.sub(r"\s+", "", safe_str(value)).upper()


def validate_meter_no(value: str, label: str, row_number: int) -> None:
    if not value:
        raise ValueError(f"{label} is blank at row {row_number}.")
    if not METER_RE.fullmatch(value):
        raise ValueError(
            f"{label} contains invalid characters at row {row_number}: {value!r}"
        )


def parse_month(value: str, label: str) -> tuple[int, int]:
    match = MONTH_RE.fullmatch(safe_str(value))
    if not match:
        raise ValueError(f"{label} must use YYYY-MM format: {value!r}")
    year, month = int(match.group(1)), int(match.group(2))
    if not 1 <= month <= 12:
        raise ValueError(f"{label} has an invalid month: {value!r}")
    return year, month


def month_range(from_month: str, to_month: str) -> list[str]:
    start_year, start_month = parse_month(from_month, "--from-month")
    end_year, end_month = parse_month(to_month, "--to-month")
    if (start_year, start_month) > (end_year, end_month):
        raise ValueError("--from-month may not be later than --to-month.")

    result: list[str] = []
    year, month = start_year, start_month
    while (year, month) <= (end_year, end_month):
        result.append(f"{year:04d}-{month:02d}")
        month += 1
        if month == 13:
            month = 1
            year += 1
    return result


def parse_iso(value: Any, label: str, row_number: int) -> datetime | None:
    text = safe_str(value)
    if not text:
        return None
    try:
        parsed = datetime.fromisoformat(text.replace("Z", "+00:00"))
    except ValueError as exc:
        raise ValueError(
            f"{label} is not a valid ISO timestamp at row {row_number}: {text!r}"
        ) from exc
    if parsed.tzinfo is None:
        raise ValueError(
            f"{label} must include a timezone at row {row_number}: {text!r}"
        )
    return parsed.astimezone(UTC)


def parse_nonnegative_int(value: Any, label: str, row_number: int) -> int:
    text = safe_str(value)
    if not text:
        raise ValueError(f"{label} is blank at row {row_number}.")
    try:
        number = Decimal(text)
    except InvalidOperation as exc:
        raise ValueError(f"{label} is not numeric at row {row_number}: {text!r}") from exc
    if number != number.to_integral_value():
        raise ValueError(f"{label} is not a whole number at row {row_number}: {text!r}")
    integer = int(number)
    if integer < 0:
        raise ValueError(f"{label} may not be negative at row {row_number}: {integer}")
    return integer


def parse_as_of_date(value: str) -> date:
    try:
        return date.fromisoformat(value)
    except ValueError as exc:
        raise ValueError(f"--as-of-date must use YYYY-MM-DD format: {value!r}") from exc


def require_file(path: Path, label: str) -> None:
    if not path.is_file():
        raise FileNotFoundError(f"{label} not found: {path}")


def require_directory(path: Path, label: str) -> None:
    if not path.is_dir():
        raise FileNotFoundError(f"{label} not found: {path}")


def sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as source:
        for block in iter(lambda: source.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def sha256_bytes(payload: bytes) -> str:
    return hashlib.sha256(payload).hexdigest()


def canonical_json_sha256(payload: Any) -> str:
    encoded = json.dumps(
        payload, sort_keys=True, separators=(",", ":"), ensure_ascii=False
    ).encode("utf-8")
    return hashlib.sha256(encoded).hexdigest()


def document_ids_sha256(values: Sequence[str]) -> str:
    return canonical_json_sha256(sorted(values))


def read_json_snapshot(path: Path, label: str) -> JsonSnapshot:
    require_file(path, label)
    raw = path.read_bytes()
    try:
        payload = json.loads(raw.decode("utf-8-sig"))
    except (UnicodeDecodeError, json.JSONDecodeError) as exc:
        raise ValueError(f"{label} is not valid JSON: {path}") from exc
    if not isinstance(payload, dict):
        raise ValueError(f"{label} must contain one JSON object: {path}")
    return JsonSnapshot(path=path, payload=payload, sha256=sha256_bytes(raw))


def read_csv_snapshot(path: Path, label: str) -> CsvSnapshot:
    require_file(path, label)
    raw = path.read_bytes()
    try:
        frame = pd.read_csv(io.BytesIO(raw), dtype=str, encoding="utf-8-sig").fillna("")
    except Exception as exc:
        raise ValueError(f"{label} is not a valid CSV: {path}") from exc
    return CsvSnapshot(path=path, frame=frame, sha256=sha256_bytes(raw))


def stage05_fingerprint_contract(manifest: Mapping[str, Any]) -> dict[str, Any]:
    source = manifest.get("sourceContract")
    output = manifest.get("outputContract")
    stats = manifest.get("stats")
    if not isinstance(source, Mapping) or not isinstance(output, Mapping) or not isinstance(stats, Mapping):
        raise ValueError("Stage 05 manifest is missing sourceContract, outputContract, or stats")
    monthly = source.get("monthlyInputs")
    if not isinstance(monthly, list):
        raise ValueError("Stage 05 manifest sourceContract.monthlyInputs must be a list")
    monthly_contract: list[dict[str, Any]] = []
    for item in monthly:
        if not isinstance(item, Mapping):
            continue
        stage03 = item.get("stage03Manifest")
        if not isinstance(stage03, Mapping):
            stage03 = {}
        atomic = stage03.get("atomicFile")
        if not isinstance(atomic, Mapping):
            atomic = {}
        reconciliation = stage03.get("reconciliation")
        if not isinstance(reconciliation, Mapping):
            reconciliation = {}
        monthly_contract.append(
            {
                "month": item.get("month"),
                "filename": item.get("filename"),
                "rows": item.get("rows"),
                "columns": item.get("columns"),
                "sha256": item.get("sha256"),
                "stage03Manifest": {
                    "filename": stage03.get("filename"),
                    "sha256": stage03.get("sha256"),
                    "atomicFile": {
                        "filename": atomic.get("filename"),
                        "rows": atomic.get("rows"),
                        "sha256": atomic.get("sha256"),
                    },
                    "reconciliation": dict(reconciliation),
                },
            }
        )
    return {
        "lmPcode": source.get("lmPcode"),
        "scope": source.get("scope"),
        "fromMonth": source.get("fromMonth"),
        "toMonth": source.get("toMonth"),
        "includedMonths": source.get("includedMonths"),
        "provider": source.get("provider"),
        "meterType": source.get("meterType"),
        "monthlyInputs": monthly_contract,
        "customerDetails": {
            "filename": (source.get("customerDetails") or {}).get("filename"),
            "rows": (source.get("customerDetails") or {}).get("rows"),
            "sha256": (source.get("customerDetails") or {}).get("sha256"),
        },
        "npr": {
            "filename": (source.get("npr") or {}).get("filename"),
            "rows": (source.get("npr") or {}).get("rows"),
            "sha256": (source.get("npr") or {}).get("sha256"),
        },
        "output": {
            "filename": output.get("filename"),
            "rows": output.get("rows"),
            "columns": output.get("columns"),
            "sha256": output.get("sha256"),
        },
        "stats": dict(stats),
    }


def validate_stage05_manifest(
    config: BuildConfig,
    months: Sequence[str],
    manifest_snapshot: JsonSnapshot,
    master_snapshot: CsvSnapshot,
    monthly_snapshots: Mapping[str, CsvSnapshot],
) -> dict[str, Any]:
    manifest = manifest_snapshot.payload
    if manifest.get("schemaVersion") != 1:
        raise ValueError("Unsupported Stage 05 manifest schemaVersion")
    if manifest.get("stage") != "05" or manifest.get("script") != "05_build_meter_master_v3.py":
        raise ValueError("Manifest is not from Stage 05")
    if manifest.get("status") != "PASS" or manifest.get("result") != "BUILD_WRITTEN":
        raise ValueError("Stage 05 manifest is not a successful frozen build")
    recorded = safe_str(manifest.get("buildFingerprint"))
    calculated = canonical_json_sha256(stage05_fingerprint_contract(manifest))
    if recorded != calculated:
        raise ValueError("Stage 05 buildFingerprint is invalid; manifest may be edited or corrupt")

    source = manifest["sourceContract"]
    output = manifest["outputContract"]
    if source.get("lmPcode") != config.lm_pcode:
        raise ValueError("Stage 05 manifest LM does not match Stage 06")
    if source.get("fromMonth") != config.from_month or source.get("toMonth") != config.to_month:
        raise ValueError("Stage 05 manifest range does not match Stage 06")
    if source.get("includedMonths") != list(months):
        raise ValueError("Stage 05 includedMonths do not match Stage 06")
    if source.get("provider") != GOVERNED_PROVIDER or source.get("meterType") != GOVERNED_METER_TYPE:
        raise ValueError("Stage 05 manifest provider or meter type is outside the governed contract")
    if output.get("filename") != config.master_path.name:
        raise ValueError("Stage 05 manifest output filename does not match --master")
    if output.get("columns") != MASTER_COLUMNS:
        raise ValueError("Stage 05 manifest Meter Master columns do not match the approved contract")
    actual_master_sha = master_snapshot.sha256
    if output.get("sha256") != actual_master_sha:
        raise ValueError("Meter Master CSV SHA-256 does not match the Stage 05 manifest")
    actual_master_rows = len(master_snapshot.frame)
    if output.get("rows") != actual_master_rows:
        raise ValueError("Meter Master CSV row count does not match the Stage 05 manifest")

    evidence = source.get("monthlyInputs")
    if not isinstance(evidence, list) or len(evidence) != len(months):
        raise ValueError("Stage 05 manifest monthly input evidence is incomplete")
    by_month = {safe_str(item.get("month")): item for item in evidence if isinstance(item, Mapping)}
    if sorted(by_month) != sorted(months):
        raise ValueError("Stage 05 manifest monthly input month set does not match Stage 06")
    validated_monthly: list[dict[str, Any]] = []
    for month in months:
        item = by_month[month]
        snapshot = monthly_snapshots[month]
        path = snapshot.path
        actual = {
            "month": month,
            "path": str(path),
            "filename": path.name,
            "rows": len(snapshot.frame),
            "columns": list(snapshot.frame.columns),
            "sha256": snapshot.sha256,
        }
        if actual["columns"] != MONTHLY_COLUMNS:
            raise ValueError(
                f"Monthly input {month} columns do not match the approved Stage 03 schema"
            )
        for field in ("filename", "rows", "columns", "sha256"):
            if item.get(field) != actual[field]:
                raise ValueError(
                    f"Monthly input {month} {field} does not match the approved Stage 05 evidence"
                )
        validated_monthly.append(actual)

    return {
        "manifestPath": str(manifest_snapshot.path),
        "manifestFilename": manifest_snapshot.path.name,
        "manifestSha256": manifest_snapshot.sha256,
        "buildFingerprint": recorded,
        "master": {
            "path": str(config.master_path),
            "filename": config.master_path.name,
            "rows": actual_master_rows,
            "columns": MASTER_COLUMNS,
            "sha256": actual_master_sha,
        },
        "monthlyInputs": validated_monthly,
    }


def utc_iso_now() -> str:
    return datetime.now(UTC).replace(microsecond=0).isoformat().replace("+00:00", "Z")


def write_csv_atomic(df: pd.DataFrame, path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_suffix(path.suffix + ".tmp")
    try:
        df.to_csv(temporary, index=False, encoding="utf-8")
        temporary.replace(path)
    finally:
        if temporary.exists():
            temporary.unlink()


def write_json_atomic(payload: Mapping[str, Any], path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_suffix(path.suffix + ".tmp")
    try:
        with temporary.open("w", encoding="utf-8", newline="\n") as target:
            json.dump(payload, target, indent=2, sort_keys=True, ensure_ascii=False)
            target.write("\n")
        temporary.replace(path)
    finally:
        if temporary.exists():
            temporary.unlink()


def build_stage06_manifest(
    config: BuildConfig,
    months: Sequence[str],
    df: pd.DataFrame,
    stats: BuildStats,
    stage05_evidence: Mapping[str, Any],
) -> dict[str, Any]:
    ids = df["masterId"].tolist()
    monthly_columns = [f"amount_{month.replace('-', '_')}_C" for month in months]
    source_contract = {
        "lmPcode": config.lm_pcode,
        "fromMonth": config.from_month,
        "toMonth": config.to_month,
        "includedMonths": list(months),
        "provider": GOVERNED_PROVIDER,
        "asOfDate": config.as_of_date.isoformat(),
        "visibilityOwnership": "OPERATIONAL_WRITERS_ONLY",
        "stage05Manifest": {
            "path": stage05_evidence["manifestPath"],
            "filename": stage05_evidence["manifestFilename"],
            "sha256": stage05_evidence["manifestSha256"],
            "buildFingerprint": stage05_evidence["buildFingerprint"],
        },
        "meterMaster": {
            **dict(stage05_evidence["master"]),
            "documentIdsSha256": document_ids_sha256(ids),
        },
        "monthlyInputs": list(stage05_evidence["monthlyInputs"]),
    }
    output_contract = {
        "path": str(config.output_path),
        "filename": config.output_path.name,
        "rows": len(df),
        "columns": list(df.columns),
        "sha256": sha256_file(config.output_path),
        "documentIdsSha256": document_ids_sha256(ids),
        "months": list(months),
        "monthlyColumns": monthly_columns,
        "provider": GOVERNED_PROVIDER,
        "totalAmountC": int(df["totalAmountC"].astype("int64").sum()),
        "visibilityColumn": "ABSENT",
    }
    stats_payload = {
        "masterRows": stats.master_rows,
        "monthlyRowsMerged": stats.monthly_rows,
        "metersWithSales": stats.meters_with_sales,
        "metersWithoutSales": stats.meters_without_sales,
        "totalOutputRows": len(df),
    }
    fingerprint_contract = {
        "lmPcode": config.lm_pcode,
        "fromMonth": config.from_month,
        "toMonth": config.to_month,
        "includedMonths": list(months),
        "provider": GOVERNED_PROVIDER,
        "asOfDate": config.as_of_date.isoformat(),
        "visibilityOwnership": "OPERATIONAL_WRITERS_ONLY",
        "stage05Manifest": {
            "filename": stage05_evidence["manifestFilename"],
            "sha256": stage05_evidence["manifestSha256"],
            "buildFingerprint": stage05_evidence["buildFingerprint"],
        },
        "meterMaster": {
            "filename": stage05_evidence["master"]["filename"],
            "rows": stage05_evidence["master"]["rows"],
            "columns": stage05_evidence["master"]["columns"],
            "sha256": stage05_evidence["master"]["sha256"],
            "documentIdsSha256": output_contract["documentIdsSha256"],
        },
        "monthlyInputs": [
            {
                "month": item["month"],
                "filename": item["filename"],
                "rows": item["rows"],
                "columns": item["columns"],
                "sha256": item["sha256"],
            }
            for item in stage05_evidence["monthlyInputs"]
        ],
        "output": {
            "filename": output_contract["filename"],
            "rows": output_contract["rows"],
            "columns": output_contract["columns"],
            "sha256": output_contract["sha256"],
            "documentIdsSha256": output_contract["documentIdsSha256"],
            "months": output_contract["months"],
            "provider": output_contract["provider"],
            "totalAmountC": output_contract["totalAmountC"],
            "visibilityColumn": output_contract["visibilityColumn"],
        },
        "stats": stats_payload,
    }
    return {
        "schemaVersion": MANIFEST_SCHEMA_VERSION,
        "stage": "06",
        "script": "06_build_sales_all_meters.py",
        "status": "PASS",
        "result": "BUILD_WRITTEN",
        "createdAt": utc_iso_now(),
        "sourceContract": source_contract,
        "outputContract": output_contract,
        "stats": stats_payload,
        "buildFingerprint": canonical_json_sha256(fingerprint_contract),
    }


def discover_monthly_files(monthly_dir: Path, months: Iterable[str]) -> dict[str, Path]:
    expected_months = list(months)
    discovered: dict[str, Path] = {}

    for path in monthly_dir.iterdir():
        if not path.is_file():
            continue
        match = MONTHLY_FILENAME_RE.fullmatch(path.name)
        if not match:
            continue
        ym = match.group(1)
        if ym not in expected_months:
            continue
        if ym in discovered:
            raise ValueError(
                f"Multiple monthly files found for {ym}: {discovered[ym]} and {path}"
            )
        discovered[ym] = path.resolve()

    missing = [ym for ym in expected_months if ym not in discovered]
    if missing:
        raise FileNotFoundError(
            "Required monthly meter-level files are missing for: " + ", ".join(missing)
        )

    return {ym: discovered[ym] for ym in expected_months}


def validate_output_identity(
    path: Path,
    lm_pcode: str,
    from_month: str,
    to_month: str,
) -> None:
    expected_name = (
        f"sales_all_meters__{lm_pcode}__FULL__{from_month}_to_{to_month}.csv"
    )
    if path.parent.resolve() != GOVERNED_OUTPUT_DIR:
        raise ValueError(
            "Stage 06 output must be written to the governed output directory: "
            f"expected {GOVERNED_OUTPUT_DIR}, found {path.parent.resolve()}"
        )
    if path.name != expected_name:
        raise ValueError(
            "Stage 06 output filename must match the governed identity exactly: "
            f"expected {expected_name!r}, found {path.name!r}"
        )


def load_master(
    config: BuildConfig,
    stats: BuildStats,
    snapshot: CsvSnapshot,
) -> dict[str, dict[str, Any]]:
    df = snapshot.frame.copy()
    actual_columns = list(df.columns)
    if actual_columns != MASTER_COLUMNS:
        raise ValueError(
            "Meter Master columns do not match the approved ten-column contract. "
            f"Expected={MASTER_COLUMNS}; actual={actual_columns}"
        )
    if df.empty:
        raise ValueError("Meter Master CSV contains zero rows.")

    records: dict[str, dict[str, Any]] = {}
    for row_number, row in enumerate(df.to_dict("records"), start=2):
        master_raw = safe_str(row.get("masterId"))
        normalized_raw = safe_str(row.get("meterNoNormalized"))
        sales_raw = safe_str(row.get("salesId"))
        master_id = normalize_meter_no(master_raw)
        normalized = normalize_meter_no(normalized_raw)
        raw = safe_str(row.get("meterNoRaw"))
        lm_pcode = safe_str(row.get("lmPcode"))
        sales_id = normalize_meter_no(sales_raw)
        provider = safe_str(row.get("salesProvider"))
        meter_type = safe_str(row.get("meterType"))

        validate_meter_no(master_id, "masterId", row_number)
        validate_meter_no(normalized, "meterNoNormalized", row_number)
        validate_meter_no(sales_id, "salesId", row_number)
        for label, original, canonical in (
            ("masterId", master_raw, master_id),
            ("meterNoNormalized", normalized_raw, normalized),
            ("salesId", sales_raw, sales_id),
        ):
            if original != canonical:
                raise ValueError(
                    f"{label} must already be canonical uppercase alphanumeric text at "
                    f"row {row_number}: {original!r} -> {canonical!r}"
                )
        if master_id != normalized:
            raise ValueError(
                f"masterId must equal meterNoNormalized at row {row_number}: "
                f"{master_id!r} != {normalized!r}"
            )
        if sales_id != normalized:
            raise ValueError(
                f"salesId must equal meterNoNormalized at row {row_number}: "
                f"{sales_id!r} != {normalized!r}"
            )
        if lm_pcode != config.lm_pcode:
            raise ValueError(
                f"Meter Master LM mismatch at row {row_number}: "
                f"expected {config.lm_pcode!r}, found {lm_pcode!r}"
            )
        if provider != GOVERNED_PROVIDER:
            raise ValueError(
                f"salesProvider must be {GOVERNED_PROVIDER!r} at row {row_number}; found {provider!r}"
            )
        if meter_type != GOVERNED_METER_TYPE:
            raise ValueError(
                f"meterType must be {GOVERNED_METER_TYPE!r} at row {row_number}; found {meter_type!r}"
            )
        if master_id in records:
            raise ValueError(f"Duplicate masterId in Meter Master: {master_id!r}")

        records[master_id] = {
            "masterId": master_id,
            "meterNo": raw,
            "meterNoNormalized": normalized,
            "provider": provider,
            "customerNo": safe_str(row.get("customerNo")),
            "accountNo": safe_str(row.get("accountNo")),
            "months": {},
            "totalAmountC": 0,
            "lastPurchase": None,
        }

    stats.master_rows = len(records)
    return records


def validate_monthly_purchase(
    *,
    amount: int,
    purchase: datetime | None,
    ym: str,
    approved_months: set[str],
    path: Path,
    row_number: int,
) -> None:
    if ym not in approved_months:
        raise ValueError(
            f"{path} contains month {ym!r} outside the approved Stage 06 range."
        )
    if amount > 0 and purchase is None:
        raise ValueError(
            f"{path} has positive amountTotalC but blank lastPurchaseAtISO "
            f"at row {row_number}."
        )
    if purchase is not None:
        purchase_month = purchase.strftime("%Y-%m")
        if purchase_month != ym:
            raise ValueError(
                f"{path} lastPurchaseAtISO belongs to {purchase_month!r} at row "
                f"{row_number}; expected the applicable sales month {ym!r}."
            )


def load_monthly_files(
    config: BuildConfig,
    monthly_snapshots: Mapping[str, CsvSnapshot],
    records: dict[str, dict[str, Any]],
    stats: BuildStats,
) -> None:
    unknown_meters: list[tuple[str, str, int]] = []

    approved_months = set(month_range(config.from_month, config.to_month))
    for ym, snapshot in monthly_snapshots.items():
        path = snapshot.path
        df = snapshot.frame.copy()
        missing_columns = [column for column in MONTHLY_REQUIRED_COLUMNS if column not in df.columns]
        if missing_columns:
            raise ValueError(f"{path} is missing required columns: {missing_columns}")

        seen_meters: set[str] = set()
        for row_number, row in enumerate(df.to_dict("records"), start=2):
            row_lm = safe_str(row.get("lmPcode"))
            row_ym = safe_str(row.get("ym"))
            meter = normalize_meter_no(row.get("meterNo"))

            if row_lm != config.lm_pcode:
                raise ValueError(
                    f"{path} contains LM {row_lm!r} at row {row_number}; "
                    f"expected only {config.lm_pcode!r}."
                )
            if row_ym != ym:
                raise ValueError(
                    f"{path} contains ym={row_ym!r} at row {row_number}; expected {ym!r}."
                )
            validate_meter_no(meter, "meterNo", row_number)
            if meter in seen_meters:
                raise ValueError(f"{path} contains duplicate meter {meter!r} for month {ym}.")
            seen_meters.add(meter)

            record = records.get(meter)
            if record is None:
                if len(unknown_meters) < 20:
                    unknown_meters.append((ym, meter, row_number))
                continue

            amount = parse_nonnegative_int(row.get("amountTotalC"), "amountTotalC", row_number)
            purchase = parse_iso(row.get("lastPurchaseAtISO"), "lastPurchaseAtISO", row_number)
            validate_monthly_purchase(
                amount=amount,
                purchase=purchase,
                ym=ym,
                approved_months=approved_months,
                path=path,
                row_number=row_number,
            )

            record["months"][ym] = amount
            record["totalAmountC"] += amount
            if amount > 0 and purchase is not None and (
                record["lastPurchase"] is None or purchase > record["lastPurchase"]
            ):
                record["lastPurchase"] = purchase
            stats.monthly_rows += 1

    if unknown_meters:
        examples = ", ".join(
            f"{ym}:{meter} (row {row_number})"
            for ym, meter, row_number in unknown_meters[:10]
        )
        raise ValueError(
            "Monthly sales contain meter(s) absent from the approved Meter Master. "
            f"Examples: {examples}"
        )


def finalize_rows(
    config: BuildConfig,
    months: list[str],
    records: dict[str, dict[str, Any]],
    stats: BuildStats,
) -> pd.DataFrame:
    rows: list[dict[str, Any]] = []
    for record in records.values():
        last_purchase: datetime | None = record["lastPurchase"]
        if record["totalAmountC"] == 0:
            last_purchase = None
        if record["totalAmountC"] > 0 and last_purchase is None:
            raise ValueError(
                f"Meter {record['masterId']} has positive totalAmountC but no valid "
                "lastPurchaseAtISO in the approved monthly range."
            )
        if last_purchase is None:
            last_purchase_iso = ""
            days_since: int | str = ""
        else:
            last_purchase_iso = last_purchase.isoformat().replace("+00:00", "Z")
            days_since_value = (config.as_of_date - last_purchase.date()).days
            if days_since_value < 0:
                raise ValueError(
                    f"Last purchase for {record['masterId']} occurs after --as-of-date: "
                    f"{last_purchase_iso} > {config.as_of_date.isoformat()}"
                )
            days_since = days_since_value

        row: dict[str, Any] = {
            "masterId": record["masterId"],
            "meterNo": record["meterNo"],
            "meterNoNormalized": record["meterNoNormalized"],
            "provider": record["provider"],
            "customerNo": record["customerNo"],
            "accountNo": record["accountNo"],
            "totalAmountC": record["totalAmountC"],
            "lastPurchaseAtISO": last_purchase_iso,
            "daysSinceLastPurchase": days_since,
        }
        for ym in months:
            row[f"amount_{ym.replace('-', '_')}_C"] = record["months"].get(ym, 0)
        rows.append(row)

        if record["totalAmountC"] > 0:
            stats.meters_with_sales += 1
        else:
            stats.meters_without_sales += 1
    monthly_columns = [f"amount_{ym.replace('-', '_')}_C" for ym in months]
    output_columns = BASE_OUTPUT_COLUMNS + monthly_columns
    df = pd.DataFrame(rows, columns=output_columns)
    return df.sort_values(
        by=["meterNoNormalized", "meterNo"],
        ascending=[True, True],
        kind="stable",
    ).reset_index(drop=True)


def validate_output(df: pd.DataFrame, months: list[str], expected_rows: int) -> None:
    if len(df) != expected_rows:
        raise ValueError(f"Output row count mismatch: expected {expected_rows}, found {len(df)}")
    if df.empty:
        raise ValueError("Sales All Meters output contains zero rows.")
    if df["masterId"].eq("").any():
        raise ValueError("Sales All Meters output contains blank masterId values.")
    if df["masterId"].duplicated().any():
        examples = df.loc[df["masterId"].duplicated(keep=False), "masterId"].head(10).tolist()
        raise ValueError(f"Sales All Meters output contains duplicate masterId values: {examples}")
    if not (df["masterId"] == df["meterNoNormalized"]).all():
        raise ValueError("Sales All Meters output contains masterId/meterNoNormalized mismatches.")
    if "visibility" in df.columns:
        raise ValueError(
            "Sales All Meters staging must not contain visibility; "
            "operational registration/discovery/installation writers own master.visibility."
        )

    positive = df["totalAmountC"].astype("int64") > 0
    if df.loc[positive, "lastPurchaseAtISO"].astype(str).str.strip().eq("").any():
        raise ValueError(
            "Sales All Meters output has positive totalAmountC with blank lastPurchaseAtISO."
        )
    if df.loc[positive, "daysSinceLastPurchase"].astype(str).str.strip().eq("").any():
        raise ValueError(
            "Sales All Meters output has positive totalAmountC with blank daysSinceLastPurchase."
        )
    no_sales = ~positive
    if df.loc[no_sales, "lastPurchaseAtISO"].astype(str).str.strip().ne("").any():
        raise ValueError(
            "Sales All Meters output has zero totalAmountC with populated lastPurchaseAtISO."
        )
    if df.loc[no_sales, "daysSinceLastPurchase"].astype(str).str.strip().ne("").any():
        raise ValueError(
            "Sales All Meters output has zero totalAmountC with populated daysSinceLastPurchase."
        )

    monthly_columns = [f"amount_{ym.replace('-', '_')}_C" for ym in months]
    calculated_totals = df[monthly_columns].astype("int64").sum(axis=1)
    reported_totals = df["totalAmountC"].astype("int64")
    mismatches = calculated_totals != reported_totals
    if mismatches.any():
        sample = df.loc[mismatches, ["masterId", "totalAmountC"] + monthly_columns].head(10)
        raise ValueError(
            "totalAmountC does not reconcile to the included monthly columns. Examples:\n"
            + sample.to_string(index=False)
        )


def build_config(args: argparse.Namespace) -> BuildConfig:
    lm_pcode = safe_str(args.lm_pcode).upper()
    if not lm_pcode:
        raise ValueError("--lm-pcode may not be blank.")
    months = month_range(args.from_month, args.to_month)
    if not months:
        raise ValueError("The requested month range is empty.")

    output_path = resolve_project_path(args.output).resolve()
    config = BuildConfig(
        lm_pcode=lm_pcode,
        from_month=months[0],
        to_month=months[-1],
        master_path=resolve_project_path(args.master).resolve(),
        master_manifest_path=resolve_project_path(args.master_manifest).resolve(),
        monthly_dir=resolve_project_path(args.monthly_dir).resolve(),
        output_path=output_path,
        manifest_path=output_path.with_suffix(".manifest.json"),
        as_of_date=parse_as_of_date(args.as_of_date),
    )
    validate_output_identity(
        config.output_path,
        config.lm_pcode,
        config.from_month,
        config.to_month,
    )
    return config


def main() -> None:
    args = parse_args()
    config = build_config(args)
    months = month_range(config.from_month, config.to_month)
    stats = BuildStats()

    require_file(config.master_path, "Meter Master CSV")
    require_file(config.master_manifest_path, "Stage 05 manifest")
    require_directory(config.monthly_dir, "Monthly output directory")
    monthly_files = discover_monthly_files(config.monthly_dir, months)
    manifest_snapshot = read_json_snapshot(config.master_manifest_path, "Stage 05 manifest")
    master_snapshot = read_csv_snapshot(config.master_path, "Meter Master CSV")
    monthly_snapshots = {
        month: read_csv_snapshot(path, f"Monthly input {month}")
        for month, path in monthly_files.items()
    }
    stage05_evidence = validate_stage05_manifest(
        config,
        months,
        manifest_snapshot,
        master_snapshot,
        monthly_snapshots,
    )

    print("=== SALES ALL METERS BUILD ===")
    print(f"Repository root: {PROJECT_ROOT}")
    print(f"LM/workbase:     {config.lm_pcode}")
    print(f"Meter Master:    {config.master_path}")
    print(f"Stage 05 manifest: {config.master_manifest_path}")
    print(f"As-of date:      {config.as_of_date.isoformat()}")
    print(f"Months:          {len(months)} ({months[0]} to {months[-1]})")
    for ym, path in monthly_files.items():
        print(f"  - {ym}: {path}")

    records = load_master(config, stats, master_snapshot)
    load_monthly_files(config, monthly_snapshots, records, stats)
    df = finalize_rows(config, months, records, stats)
    validate_output(df, months, stats.master_rows)

    write_csv_atomic(df, config.output_path)
    manifest = build_stage06_manifest(config, months, df, stats, stage05_evidence)
    write_json_atomic(manifest, config.manifest_path)

    print("=== BUILD SUMMARY ===")
    print(f"Meter Master rows:       {stats.master_rows:,}")
    print(f"Monthly rows merged:     {stats.monthly_rows:,}")
    print(f"Meters with sales:       {stats.meters_with_sales:,}")
    print(f"Meters without sales:    {stats.meters_without_sales:,}")
    print(f"Total output rows:       {len(df):,}")
    print("Total reconciliation:    PASS")
    print("Validation:              PASS")
    print(f"Output:                  {config.output_path}")
    print(f"Output SHA-256:           {manifest['outputContract']['sha256']}")
    print(f"Build fingerprint:       {manifest['buildFingerprint']}")
    print(f"Manifest:                {config.manifest_path}")


if __name__ == "__main__":
    main()
