"""
07_upload_meter_master_v3.py

Reusable, once-off uploader for the approved Meter Master staging CSV.

Design goals
------------
- No hard-coded Firebase project, service account, or input CSV.
- The same approved CSV can be uploaded to TEST, Trials, and Production.
- The service-account project must match --project-id.
- --confirm-project must exactly match --project-id.
- create-only mode requires an empty meter_master collection.
- resume mode creates only missing documents, skips matching documents,
  and stops before writing if any conflicting document is found.
- Every created document receives the six mandatory metadata fields.
- A SHA-256 fingerprint and JSON run report provide traceability.

Example: first upload to TEST
-----------------------------
python .\\scripts\\07_upload_meter_master_v3.py `
  --project-id ireps-test `
  --confirm-project ireps-test `
  --service-account .\\secrets\\ireps-test.json `
  --input .\\output\\meter_master\\meter_master__ZA7423__FULL__2025-09_to_2026-06.csv `
  --mode create-only

Example: recover after a partial upload
---------------------------------------
python .\\scripts\\07_upload_meter_master_v3.py `
  --project-id ireps-test `
  --confirm-project ireps-test `
  --service-account .\\secrets\\ireps-test.json `
  --input .\\output\\meter_master\\meter_master__ZA7423__FULL__2025-09_to_2026-06.csv `
  --mode resume
"""

from __future__ import annotations

import argparse
import hashlib
import json
from dataclasses import dataclass
from datetime import UTC, datetime
from pathlib import Path
from typing import Any, Iterable, Iterator, Mapping, Sequence

import pandas as pd
from google.cloud import firestore
from google.oauth2 import service_account
from tqdm import tqdm


PROJECT_ROOT = Path(__file__).resolve().parents[1]
COLLECTION_NAME = "meter_master"
BATCH_SIZE = 450
SYSTEM_UID = "SYSTEM"
SYSTEM_USER = "METER MASTER PIPELINE"

REQUIRED_COLUMNS = [
    "masterId",
    "lmPcode",
    "meterNoRaw",
    "meterNoNormalized",
    "meterType",
    "customerNo",
    "accountNo",
    "salesId",
    "salesProvider",
    "astId",
]

ALLOWED_TOP_LEVEL_FIELDS = {
    "lmPcode",
    "meterNo",
    "meterType",
    "customerNo",
    "accountNo",
    "refs",
    "metadata",
}
METADATA_FIELDS = {
    "createdAt",
    "createdByUid",
    "createdByUser",
    "updatedAt",
    "updatedByUid",
    "updatedByUser",
}


@dataclass(frozen=True)
class UploadConfig:
    project_id: str
    confirm_project: str
    service_account_path: Path
    input_path: Path
    mode: str
    report_dir: Path


@dataclass
class PreflightResult:
    row_count: int
    unique_master_ids: int
    csv_sha256: str
    lm_pcodes: list[str]
    providers: list[str]


@dataclass
class ResumePlan:
    missing_rows: list[dict[str, str]]
    matching_count: int
    conflicts: list[dict[str, Any]]
    extra_document_ids: list[str]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Upload an approved Meter Master CSV to an explicitly selected Firebase project."
    )
    parser.add_argument("--project-id", required=True, help="Target Firebase project ID.")
    parser.add_argument(
        "--confirm-project",
        required=True,
        help="Must exactly repeat --project-id. Prevents accidental project selection.",
    )
    parser.add_argument(
        "--service-account",
        required=True,
        type=Path,
        help="Service-account JSON belonging to the target project.",
    )
    parser.add_argument(
        "--input",
        required=True,
        type=Path,
        help="Approved Meter Master staging CSV generated by 05_build_meter_master_v3.py.",
    )
    parser.add_argument(
        "--mode",
        required=True,
        choices=["create-only", "resume"],
        help="create-only requires an empty collection; resume safely completes a partial upload.",
    )
    parser.add_argument(
        "--report-dir",
        type=Path,
        default=Path("output/logs/meter_master"),
        help="Directory for the JSON upload report. Relative paths resolve from the repository root.",
    )
    return parser.parse_args()


def resolve_project_path(path: Path) -> Path:
    return path if path.is_absolute() else PROJECT_ROOT / path


def safe_str(value: Any) -> str:
    if value is None or pd.isna(value):
        return ""
    text = str(value).strip()
    return "" if text.lower() == "nan" else text


def require_file(path: Path, label: str) -> None:
    if not path.is_file():
        raise FileNotFoundError(f"{label} not found: {path}")


def read_service_account_project_id(path: Path) -> str:
    with path.open("r", encoding="utf-8") as handle:
        payload = json.load(handle)
    project_id = safe_str(payload.get("project_id"))
    if not project_id:
        raise ValueError(f"Service-account file has no project_id: {path}")
    return project_id


def sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for block in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def load_and_validate_csv(path: Path) -> tuple[pd.DataFrame, PreflightResult]:
    df = pd.read_csv(path, dtype=str, encoding="utf-8-sig").fillna("")

    actual_columns = list(df.columns)
    if actual_columns != REQUIRED_COLUMNS:
        missing = [column for column in REQUIRED_COLUMNS if column not in actual_columns]
        unexpected = [column for column in actual_columns if column not in REQUIRED_COLUMNS]
        raise ValueError(
            "Meter Master staging columns do not match the approved contract. "
            f"Expected order={REQUIRED_COLUMNS}; actual={actual_columns}; "
            f"missing={missing}; unexpected={unexpected}"
        )

    for column in REQUIRED_COLUMNS:
        df[column] = df[column].map(safe_str)

    if df.empty:
        raise ValueError("Meter Master staging CSV contains zero rows.")

    blank_master = df["masterId"] == ""
    if blank_master.any():
        raise ValueError(f"CSV contains {int(blank_master.sum())} row(s) with blank masterId.")

    duplicate_ids = df["masterId"].duplicated(keep=False)
    if duplicate_ids.any():
        examples = sorted(df.loc[duplicate_ids, "masterId"].unique().tolist())[:10]
        raise ValueError(
            f"CSV contains duplicate masterId values. Examples: {examples}"
        )

    invalid_doc_ids = df["masterId"].str.contains("/", regex=False)
    if invalid_doc_ids.any():
        examples = df.loc[invalid_doc_ids, "masterId"].head(10).tolist()
        raise ValueError(f"masterId may not contain '/'. Examples: {examples}")

    checks = {
        "lmPcode": df["lmPcode"] != "",
        "meterNoRaw": df["meterNoRaw"] != "",
        "meterNoNormalized": df["meterNoNormalized"] != "",
        "meterType": df["meterType"] != "",
        "salesId": df["salesId"] != "",
        "salesProvider": df["salesProvider"] != "",
    }
    for field, valid_mask in checks.items():
        if not valid_mask.all():
            raise ValueError(
                f"CSV contains {int((~valid_mask).sum())} row(s) with blank {field}."
            )

    id_mismatch = df["masterId"] != df["meterNoNormalized"]
    if id_mismatch.any():
        sample = df.loc[id_mismatch, ["masterId", "meterNoNormalized"]].head(10)
        raise ValueError(
            "masterId must equal meterNoNormalized. Examples:\n"
            + sample.to_string(index=False)
        )

    sales_mismatch = df["salesId"] != df["meterNoNormalized"]
    if sales_mismatch.any():
        sample = df.loc[sales_mismatch, ["salesId", "meterNoNormalized"]].head(10)
        raise ValueError(
            "salesId must equal meterNoNormalized. Examples:\n"
            + sample.to_string(index=False)
        )

    result = PreflightResult(
        row_count=len(df),
        unique_master_ids=int(df["masterId"].nunique()),
        csv_sha256=sha256_file(path),
        lm_pcodes=sorted(value for value in df["lmPcode"].unique().tolist() if value),
        providers=sorted(value for value in df["salesProvider"].unique().tolist() if value),
    )
    return df, result


def dataframe_rows(df: pd.DataFrame) -> list[dict[str, str]]:
    return [
        {column: safe_str(row.get(column)) for column in REQUIRED_COLUMNS}
        for _, row in df.iterrows()
    ]


def build_create_doc(row: Mapping[str, Any], timestamp: datetime) -> dict[str, Any]:
    return {
        "lmPcode": safe_str(row.get("lmPcode")),
        "meterNo": {
            "raw": safe_str(row.get("meterNoRaw")),
            "normalized": safe_str(row.get("meterNoNormalized")),
        },
        "meterType": safe_str(row.get("meterType")) or "electricity",
        "customerNo": safe_str(row.get("customerNo")),
        "accountNo": safe_str(row.get("accountNo")),
        "refs": {
            "asts": {"id": safe_str(row.get("astId"))},
            "sales": {
                "id": safe_str(row.get("salesId")),
                "provider": safe_str(row.get("salesProvider")) or "conlog",
            },
        },
        "metadata": {
            "createdAt": timestamp,
            "createdByUid": SYSTEM_UID,
            "createdByUser": SYSTEM_USER,
            "updatedAt": timestamp,
            "updatedByUid": SYSTEM_UID,
            "updatedByUser": SYSTEM_USER,
        },
    }


def expected_business_fields(row: Mapping[str, Any]) -> dict[str, Any]:
    """Return fields that must match during resume, excluding timestamps."""
    return {
        "lmPcode": safe_str(row.get("lmPcode")),
        "meterNo": {
            "raw": safe_str(row.get("meterNoRaw")),
            "normalized": safe_str(row.get("meterNoNormalized")),
        },
        "meterType": safe_str(row.get("meterType")) or "electricity",
        "customerNo": safe_str(row.get("customerNo")),
        "accountNo": safe_str(row.get("accountNo")),
        "refs": {
            "asts": {"id": safe_str(row.get("astId"))},
            "sales": {
                "id": safe_str(row.get("salesId")),
                "provider": safe_str(row.get("salesProvider")) or "conlog",
            },
        },
    }


def nested_get(payload: Mapping[str, Any], path: Sequence[str]) -> Any:
    current: Any = payload
    for part in path:
        if not isinstance(current, Mapping):
            return None
        current = current.get(part)
    return current


def compare_existing_document(
    existing: Mapping[str, Any], row: Mapping[str, Any]
) -> list[str]:
    """
    Compare an existing document with the staging row.

    A populated operational refs.asts.id is accepted when CSV astId is blank.
    Metadata timestamp values may differ, but all six fields must exist.
    """
    differences: list[str] = []
    expected = expected_business_fields(row)

    extra_top_level = sorted(set(existing.keys()) - ALLOWED_TOP_LEVEL_FIELDS)
    if extra_top_level:
        differences.append(f"unexpected top-level fields: {extra_top_level}")

    comparison_paths = [
        ("lmPcode",),
        ("meterNo", "raw"),
        ("meterNo", "normalized"),
        ("meterType",),
        ("customerNo",),
        ("accountNo",),
        ("refs", "sales", "id"),
        ("refs", "sales", "provider"),
    ]
    for path in comparison_paths:
        actual = nested_get(existing, path)
        wanted = nested_get(expected, path)
        if safe_str(actual) != safe_str(wanted):
            differences.append(
                f"{'.'.join(path)} existing={actual!r} expected={wanted!r}"
            )

    expected_ast_id = safe_str(nested_get(expected, ("refs", "asts", "id")))
    existing_ast_id = safe_str(nested_get(existing, ("refs", "asts", "id")))
    if expected_ast_id and existing_ast_id != expected_ast_id:
        differences.append(
            f"refs.asts.id existing={existing_ast_id!r} expected={expected_ast_id!r}"
        )

    meter_no = existing.get("meterNo")
    if not isinstance(meter_no, Mapping) or set(meter_no.keys()) != {"raw", "normalized"}:
        differences.append("meterNo must contain exactly raw and normalized")

    refs = existing.get("refs")
    if not isinstance(refs, Mapping) or set(refs.keys()) != {"asts", "sales"}:
        differences.append("refs must contain exactly asts and sales")
    else:
        asts = refs.get("asts")
        sales = refs.get("sales")
        if not isinstance(asts, Mapping) or set(asts.keys()) != {"id"}:
            differences.append("refs.asts must contain exactly id")
        if not isinstance(sales, Mapping) or set(sales.keys()) != {"id", "provider"}:
            differences.append("refs.sales must contain exactly id and provider")

    metadata = existing.get("metadata")
    if not isinstance(metadata, Mapping):
        differences.append("metadata is missing or is not an object")
    else:
        missing_metadata = sorted(METADATA_FIELDS - set(metadata.keys()))
        extra_metadata = sorted(set(metadata.keys()) - METADATA_FIELDS)
        if missing_metadata:
            differences.append(f"metadata missing fields: {missing_metadata}")
        if extra_metadata:
            differences.append(f"metadata has unexpected fields: {extra_metadata}")

    return differences


def chunks(items: Sequence[Any], size: int) -> Iterator[Sequence[Any]]:
    for start in range(0, len(items), size):
        yield items[start : start + size]


def collection_has_documents(db: firestore.Client) -> bool:
    return next(db.collection(COLLECTION_NAME).limit(1).stream(), None) is not None


def create_documents(
    db: firestore.Client,
    rows: Sequence[Mapping[str, Any]],
    timestamp: datetime,
) -> int:
    written = 0
    for row_batch in tqdm(
        list(chunks(rows, BATCH_SIZE)),
        desc="Writing Meter Master batches",
        unit="batch",
    ):
        batch = db.batch()
        for row in row_batch:
            doc_id = safe_str(row.get("masterId"))
            doc_ref = db.collection(COLLECTION_NAME).document(doc_id)
            batch.create(doc_ref, build_create_doc(row, timestamp))
        batch.commit()
        written += len(row_batch)
    return written


def build_resume_plan(
    db: firestore.Client,
    rows: Sequence[dict[str, str]],
) -> ResumePlan:
    missing_rows: list[dict[str, str]] = []
    conflicts: list[dict[str, Any]] = []
    matching_count = 0

    row_by_id = {row["masterId"]: row for row in rows}
    ids = list(row_by_id.keys())

    for id_batch in tqdm(
        list(chunks(ids, BATCH_SIZE)),
        desc="Checking existing Meter Master documents",
        unit="batch",
    ):
        refs = [db.collection(COLLECTION_NAME).document(doc_id) for doc_id in id_batch]
        snapshots_by_id = {snapshot.id: snapshot for snapshot in db.get_all(refs)}

        for doc_id in id_batch:
            row = row_by_id[doc_id]
            snapshot = snapshots_by_id.get(doc_id)
            if snapshot is None or not snapshot.exists:
                missing_rows.append(row)
                continue

            differences = compare_existing_document(snapshot.to_dict() or {}, row)
            if differences:
                conflicts.append({"masterId": doc_id, "differences": differences})
            else:
                matching_count += 1

    existing_collection_ids = {
        snapshot.id for snapshot in db.collection(COLLECTION_NAME).stream()
    }
    extra_document_ids = sorted(existing_collection_ids - set(ids))
    for doc_id in extra_document_ids[:100]:
        conflicts.append(
            {
                "masterId": doc_id,
                "differences": ["document exists in Firestore but is absent from the approved CSV"],
            }
        )

    return ResumePlan(
        missing_rows=missing_rows,
        matching_count=matching_count,
        conflicts=conflicts,
        extra_document_ids=extra_document_ids,
    )


def make_report_path(report_dir: Path, project_id: str) -> Path:
    timestamp = datetime.now(UTC).strftime("%Y%m%dT%H%M%SZ")
    return report_dir / f"meter_master_upload__{project_id}__{timestamp}.json"


def write_report(report_path: Path, payload: Mapping[str, Any]) -> None:
    report_path.parent.mkdir(parents=True, exist_ok=True)
    with report_path.open("w", encoding="utf-8") as handle:
        json.dump(payload, handle, indent=2, default=str)
        handle.write("\n")


def print_preflight(config: UploadConfig, result: PreflightResult) -> None:
    print("\n=== METER MASTER UPLOAD PREFLIGHT ===")
    print(f"Target project:     {config.project_id}")
    print(f"Collection:         {COLLECTION_NAME}")
    print(f"Mode:               {config.mode}")
    print(f"Input CSV:          {config.input_path}")
    print(f"Rows:               {result.row_count:,}")
    print(f"Unique master IDs:  {result.unique_master_ids:,}")
    print(f"LM/workbase values: {', '.join(result.lm_pcodes)}")
    print(f"Providers:          {', '.join(result.providers)}")
    print(f"CSV SHA-256:        {result.csv_sha256}")
    print("=======================================\n")


def build_config(args: argparse.Namespace) -> UploadConfig:
    project_id = safe_str(args.project_id)
    confirm_project = safe_str(args.confirm_project)
    if not project_id:
        raise ValueError("--project-id may not be blank.")
    if confirm_project != project_id:
        raise ValueError(
            f"Project confirmation failed: --project-id={project_id!r}, "
            f"--confirm-project={confirm_project!r}"
        )

    return UploadConfig(
        project_id=project_id,
        confirm_project=confirm_project,
        service_account_path=resolve_project_path(args.service_account),
        input_path=resolve_project_path(args.input),
        mode=args.mode,
        report_dir=resolve_project_path(args.report_dir),
    )


def main() -> None:
    args = parse_args()
    config = build_config(args)
    started_at = datetime.now(UTC)
    report_path = make_report_path(config.report_dir, config.project_id)

    report: dict[str, Any] = {
        "operation": "meter_master_once_off_upload",
        "projectId": config.project_id,
        "collection": COLLECTION_NAME,
        "mode": config.mode,
        "inputPath": str(config.input_path),
        "serviceAccountPath": str(config.service_account_path),
        "startedAt": started_at.isoformat(),
        "status": "STARTED",
    }

    try:
        require_file(config.input_path, "Input CSV")
        require_file(config.service_account_path, "Service-account file")

        credential_project = read_service_account_project_id(config.service_account_path)
        report["credentialProjectId"] = credential_project
        if credential_project != config.project_id:
            raise ValueError(
                "Service-account project mismatch. "
                f"Requested={config.project_id!r}; credential={credential_project!r}"
            )

        df, preflight = load_and_validate_csv(config.input_path)
        rows = dataframe_rows(df)
        report.update(
            {
                "csvSha256": preflight.csv_sha256,
                "rowsRead": preflight.row_count,
                "uniqueMasterIds": preflight.unique_master_ids,
                "lmPcodes": preflight.lm_pcodes,
                "providers": preflight.providers,
            }
        )
        print_preflight(config, preflight)

        credentials = service_account.Credentials.from_service_account_file(
            str(config.service_account_path)
        )
        db = firestore.Client(project=config.project_id, credentials=credentials)

        operation_timestamp = datetime.now(UTC)

        if config.mode == "create-only":
            if collection_has_documents(db):
                raise RuntimeError(
                    f"Upload blocked: {COLLECTION_NAME} is not empty in {config.project_id}. "
                    "Use --mode resume only for recovery from a verified partial upload."
                )
            written = create_documents(db, rows, operation_timestamp)
            matching = 0
            missing_before = len(rows)

        else:
            plan = build_resume_plan(db, rows)
            report["matchingDocuments"] = plan.matching_count
            report["missingDocumentsBeforeWrite"] = len(plan.missing_rows)
            report["conflictCount"] = len(plan.conflicts)
            report["extraDocumentCount"] = len(plan.extra_document_ids)
            if plan.extra_document_ids:
                report["extraDocumentIds"] = plan.extra_document_ids[:100]
            if plan.conflicts:
                report["conflicts"] = plan.conflicts[:100]
                raise RuntimeError(
                    f"Resume blocked: {len(plan.conflicts)} conflicting document(s) found. "
                    f"See report: {report_path}"
                )
            written = create_documents(db, plan.missing_rows, operation_timestamp)
            matching = plan.matching_count
            missing_before = len(plan.missing_rows)

        final_count = sum(1 for _ in db.collection(COLLECTION_NAME).stream())
        expected_count = preflight.unique_master_ids
        if final_count != expected_count:
            raise RuntimeError(
                f"Post-upload verification failed: collection count={final_count}, "
                f"expected exactly {expected_count}."
            )

        report.update(
            {
                "documentsWritten": written,
                "matchingDocuments": matching,
                "missingDocumentsBeforeWrite": missing_before,
                "finalCollectionCount": final_count,
                "status": "PASSED",
            }
        )
        print("=== METER MASTER UPLOAD COMPLETE ===")
        print(f"Project:            {config.project_id}")
        print(f"Documents written:  {written:,}")
        print(f"Existing matching:  {matching:,}")
        print(f"Final collection:   {final_count:,}")
        print(f"Run report:         {report_path}")

    except Exception as exc:
        report["status"] = "FAILED"
        report["error"] = f"{type(exc).__name__}: {exc}"
        raise

    finally:
        report["finishedAt"] = datetime.now(UTC).isoformat()
        write_report(report_path, report)


if __name__ == "__main__":
    main()
